version: 2.1

orbs:
  python: circleci/python@2.1.1
  docker: circleci/docker@2.2.0
  heroku: circleci/heroku@2.0.0

jobs:
  tests_and_linting:
    docker:
      -image: cimg/python:3.10.6
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
        name: Run linting
        command: flake8
      - run:
        name: Run tests
        command: pytest
  
  build_and_push_docker:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: ${DOCKER_USERNAME}/lettings
      - docker/push:
          image: ${DOCKER_USERNAME}/lettings
  
  deploy_to_heroku:
    docker:
      - image: cimg/python:3.10.6
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          branch: master

workflow:
  deploy_lettings_site:
    jobs:
      - tests_and_linting
      - build_and_push_docker:
        requires:
          - tests_and_linting
        filters:
          branches:
            only: master
      - deploy_to_heroku:
        requires:
          - build_and_push_docker
        filters:
          branches:
            only: master

